name: Issue Template
description: Please fill out the following information to help us resolve your issue.
title: "[ISSUE] "
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Issue Description
        Please provide a brief description of the issue you are encountering.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide detailed steps to reproduce the issue:"
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3

  - type: textarea
    id: expected-results
    attributes:
      label: "Expected Results"
      description: "What do you expect to happen?"

  - type: textarea
    id: actual-results
    attributes:
      label: "Actual Results"
      description: "What actually happens?"

  - type: markdown
    attributes:
      value: |
        ## Environment Information
        Please provide the following information:

  - type: input
    id: operating-system
    attributes:
      label: "Operating System"
      description: "e.g., Windows, macOS, Linux"

  - type: input
    id: browser
    attributes:
      label: "Browser (if applicable)"
      description: "e.g., Chrome, Firefox"

  - type: input
    id: version
    attributes:
      label: "Version"
      description: "e.g., v1.0.0"

  - type: input
    id: branch
    attributes:
      label: "Branch"
      description: "Please specify the branch you are working on (e.g., feature/branch-name, bugfix/branch-name)."

  - type: textarea
    id: additional-information
    attributes:
      label: "Additional Information"
      description: "Please add any other relevant information, screenshots, or logs here."